### ISSUE TITLE
Add support for 32u4 boards

### ISSUE THREAD

**Issue by davidbitton** [prickle/Mavpixel#5]
First off, this runs great on a Pro Mini. I then went and wired up a Pro Micro and yeah, it wouldn't compile. I've seen [FastSerial w/ 32u4 "Leo" support](https://github.com/DevFor8/Mav2Duplex), but dropping it in still didn't do the trick. Any desire to get this working on a 32u4 board? Thanks!

**Comment by prickle** [comment]
Thanks for trying Mavpixel! Sorry, no dice. Due to a number of reasons Mavpixel cannot run on a Leonardo, Pro Micro or any other Arduino variant. Mavpixel is targeted for and only works properly on a Pro Mini.
