### ISSUE TITLE
Mavpixel GUI not Flashing

### ISSUE THREAD

**Issue by Shaun055** [prickle/Mavpixel#8]
i used a cp210x to connect my new arduino pro mini 5v and tried using the MavPixelGUI to flash the mini but it fails every time. i keep getting the same message over:

"stk500_getsync(): not in sync: resp=0x60No response from Mavpixel. Check the connections and port is correct."

I tried using IDE to write the mavpixel onto the mini but that doesn't work as it says:
"Using library FastSerial in folder: C:\Users\...\libraries\FastSerial (legacy)
exit status 1
Error compiling for board Arduino Pro or Pro Mini."

Is there another version of mavpixel i need to use or so?
I'd Appreciate the help

**Comment by prickle** [comment]
Hi. Sounds like MavpixelGUI's internal copy of Avrdude cannot talk to your board. Does using Arduino IDE to flash the blink sketch work? 

Note that FastSerial is legacy code used with the Mavlink library inherited from JD-IOBoard. It may require an (possibly much) earlier version of Arduino to be able to compile properly. I can't recall which one I used, maybe 1.0.6

**Comment by Shaun055** [comment]
Hi, i tried using IDE version 1.0.6 and opened the mavlink sketch from the mavpixel master folder--> jD_IOBoard_MAVLink. and this is the error i get

Arduino: 1.0.6 (Windows NT (unknown)), Board: "Arduino Pro or Pro Mini (5V, 16 MHz) w/ ATmega328"
MAVLink:30: error: expected constructor, destructor, or type conversion before '*' token
MAVLink:31: error: expected constructor, destructor, or type conversion before '*' token
MAVLink:33: error: 'mavlink_system_t' does not name a type
MAVLink:35: error: expected constructor, destructor, or type conversion before string constant
MAVLink.ino: In function 'void request_mavlink_rates()':
MAVLink:57: error: 'DPL' was not declared in this scope
MAVLink:60: error: 'MAV_DATA_STREAM_RAW_SENSORS' was not declared in this scope
MAVLink:61: error: 'MAV_DATA_STREAM_EXTENDED_STATUS' was not declared in this scope
MAVLink:62: error: 'MAV_DATA_STREAM_RC_CHANNELS' was not declared in this scope
MAVLink:63: error: 'MAV_DATA_STREAM_POSITION' was not declared in this scope
MAVLink:64: error: 'MAV_DATA_STREAM_EXTRA1' was not declared in this scope
MAVLink:65: error: 'MAV_DATA_STREAM_EXTRA2' was not declared in this scope
MAVLink:66: error: 'MAV_DATA_STREAM_EXTRA3' was not declared in this scope
MAVLink:71: error: 'MAVLINK_COMM_0' was not declared in this scope
MAVLink:72: error: 'apm_mav_system' was not declared in this scope
MAVLink:72: error: 'apm_mav_component' was not declared in this scope
MAVLink:73: error: 'mavlink_msg_request_data_stream_send' was not declared in this scope
MAVLink.ino: In function 'void read_mavlink()':
MAVLink:78: error: 'mavlink_message_t' was not declared in this scope
MAVLink:78: error: expected `;' before 'msg'
MAVLink:79: error: 'mavlink_status_t' was not declared in this scope
MAVLink:79: error: expected `;' before 'status'
MAVLink:87: error: 'mavlink_active' was not declared in this scope
MAVLink:89: error: 'crlf_count' was not declared in this scope
MAVLink:91: error: 'crlf_count' was not declared in this scope
MAVLink:96: error: 'MAVLINK_COMM_0' was not declared in this scope
MAVLink:96: error: 'msg' was not declared in this scope
MAVLink:96: error: 'status' was not declared in this scope
MAVLink:96: error: 'mavlink_parse_char' was not declared in this scope
MAVLink:98: error: 'mavlink_active' was not declared in this scope
MAVLink:99: error: 'LeRiPatt' was not declared in this scope
MAVLink:103: error: 'MAVLINK_MSG_ID_HEARTBEAT' was not declared in this scope
MAVLink:105: error: 'DPL' was not declared in this scope
MAVLink:106: error: 'mavbeat' was not declared in this scope
MAVLink:107: error: 'apm_mav_system' was not declared in this scope
MAVLink:108: error: 'apm_mav_component' was not declared in this scope
MAVLink:109: error: 'apm_mav_type' was not declared in this scope
MAVLink:109: error: 'mavlink_msg_heartbeat_get_type' was not declared in this scope
MAVLink:111: error: 'iob_mode' was not declared in this scope
MAVLink:111: error: 'mavlink_msg_heartbeat_get_custom_mode' was not declared in this scope
MAVLink:112: error: 'iob_old_mode' was not declared in this scope
MAVLink:114: error: 'CheckFlightMode' was not declared in this scope
MAVLink:116: error: 'iob_nav_mode' was not declared in this scope
MAVLink:119: error: 'mavlink_msg_heartbeat_get_base_mode' was not declared in this scope
MAVLink:119: error: 'MOTORS_ARMED' was not declared in this scope
MAVLink:119: error: 'isBit' was not declared in this scope
MAVLink:120: error: 'isArmedOld' was not declared in this scope
MAVLink:121: error: 'CheckFlightMode' was not declared in this scope
MAVLink:123: error: 'Alti_SR' was not declared in this scope
MAVLink:124: error: 'Batt_SR' was not declared in this scope
MAVLink:126: error: 'isArmed' was not declared in this scope
MAVLink:128: error: 'isArmed' was not declared in this scope
MAVLink:129: error: 'isArmedOld' was not declared in this scope
MAVLink:132: error: 'lastMAVBeat' was not declared in this scope
MAVLink:159: error: 'MAVLINK_MSG_ID_SYS_STATUS' was not declared in this scope
MAVLink:163: error: 'iob_vbat_A' was not declared in this scope
MAVLink:163: error: 'mavlink_msg_sys_status_get_voltage_battery' was not declared in this scope
MAVLink:164: error: 'iob_battery_remaining_A' was not declared in this scope
MAVLink:164: error: 'mavlink_msg_sys_status_get_battery_remaining' was not declared in this scope
MAVLink:170: error: 'Batt_SR' was not declared in this scope
MAVLink:170: error: 'TRUE' was not declared in this scope
MAVLink:174: error: 'Batt_Volte_Backup' was not declared in this scope
MAVLink:178: error: 'Batt_Cell_Detect' was not declared in this scope
MAVLink:182: error: 'Batt_Cell_Detect' was not declared in this scope
MAVLink:186: error: 'Batt_Cell_Detect' was not declared in this scope
MAVLink:190: error: 'Batt_Cell_Detect' was not declared in this scope
MAVLink:192: error: 'Frsky_Count_Order_Batt' was not declared in this scope
MAVLink:217: error: 'MAVLINK_MSG_ID_GPS_RAW' was not declared in this scope
MAVLink:220: error: 'iob_fix_type' was not declared in this scope
MAVLink:220: error: 'mavlink_msg_gps_raw_get_fix_type' was not declared in this scope
MAVLink:226: error: 'MAVLINK_MSG_ID_GPS_STATUS' was not declared in this scope
MAVLink:228: error: 'DPL' was not declared in this scope
MAVLink:229: error: 'iob_satellites_visible' was not declared in this scope
MAVLink:229: error: 'mavlink_msg_gps_status_get_satellites_visible' was not declared in this scope
MAVLink:281: error: 'MAVLINK_MSG_ID_VFR_HUD' was not declared in this scope
MAVLink:283: error: 'iob_groundspeed' was not declared in this scope
MAVLink:283: error: 'mavlink_msg_vfr_hud_get_groundspeed' was not declared in this scope
MAVLink:284: error: 'iob_heading' was not declared in this scope
MAVLink:284: error: 'mavlink_msg_vfr_hud_get_heading' was not declared in this scope
MAVLink:285: error: 'iob_throttle' was not declared in this scope
MAVLink:285: error: 'mavlink_msg_vfr_hud_get_throttle' was not declared in this scope
MAVLink:288: error: 'iob_alt' was not declared in this scope
MAVLink:288: error: 'mavlink_msg_vfr_hud_get_alt' was not declared in this scope
MAVLink:292: error: 'MAVLINK_MSG_ID_SCALED_PRESSURE' was not declared in this scope
MAVLink:294: error: 'iob_temperature' was not declared in this scope
MAVLink:294: error: 'mavlink_msg_scaled_pressure_get_temperature' was not declared in this scope
MAVLink:298: error: 'MAVLINK_MSG_ID_ATTITUDE' was not declared in this scope
MAVLink:301: error: 'iob_pitch' was not declared in this scope
MAVLink:301: error: 'mavlink_msg_attitude_get_pitch' was not declared in this scope
MAVLink:301: error: 'ToDeg' was not declared in this scope
MAVLink:302: error: 'iob_roll' was not declared in this scope
MAVLink:302: error: 'mavlink_msg_attitude_get_roll' was not declared in this scope
MAVLink:303: error: 'iob_yaw' was not declared in this scope
MAVLink:303: error: 'mavlink_msg_attitude_get_yaw' was not declared in this scope
MAVLink:306: error: 'MAVLINK_MSG_ID_HWSTATUS' was not declared in this scope
MAVLink:309: error: 'boardVoltage' was not declared in this scope
MAVLink:309: error: 'mavlink_msg_hwstatus_get_Vcc' was not declared in this scope
MAVLink:310: error: 'i2cErrorCount' was not declared in this scope
MAVLink:310: error: 'mavlink_msg_hwstatus_get_I2Cerr' was not declared in this scope
MAVLink:313: error: 'voltAlarm' was not declared in this scope
MAVLink:314: error: 'voltAlarm' was not declared in this scope
MAVLink:317: error: 'MAVLINK_MSG_ID_STATUSTEXT' was not declared in this scope
MAVLink:319: error: 'mavlink_msg_statustext_get_severity' was not declared in this scope
MAVLink:319: error: 'DPL' was not declared in this scope
MAVLink:331: error: 'status' was not declared in this scope
MAVLink.ino: In function 'void cellVvalue()':
MAVLink:339: error: 'iob_vbat_A' was not declared in this scope
MAVLink:339: error: 'cell_numb' was not declared in this scope
MAVLink:342: error: 'MAXCELL' was not declared in this scope
MAVLink:348: error: 'cellV' was not declared in this scope

**Comment by Shaun055** [comment]
is there another version of Mavpixel GUI i can use or some other avr exe?

**Comment by Shaun055** [comment]
Never mind i just solved the issue,,,
problem was the AVR wasn't running the bootloader, so what i did was press the RESET button on the mini, while MavPixel was flashing the mini, worked like a charm
